###############################################################
#  Generated by:      Cadence Encounter 11.12-s136_1
#  OS:                Linux x86_64(Host ID thor.doe.carleton.ca)
#  Generated on:      Wed Mar 11 01:26:21 2020
#  Design:            allocation_buffer
#  Command:           saveDesign allocation_buffer.enc
###############################################################
set sdc_version 1.4
current_design allocation_buffer
create_clock [get_ports {clk}]  -name clk -period 10.000000 -waveform {0.000000 5.000000}
set_propagated_clock  [get_ports {clk}]
set_false_path  -from [get_ports {rst}] 
